name: Build EXE with PyInstaller

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --name netwave-tx main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: netwave-tx_exe
          path: dist/netwave-tx.exe
